### ISSUE TITLE
Why L2 norm then CosSim?

### ISSUE THREAD

**Issue by BoPang1996** [Spijkervet/SimCLR#15]
Hi, This code is really useful for me. Thanks!
But I got a question about the NT-Xent loss. I noticed that you use L2 norm on z and then use cos_similarity after that. But cos_similarity already contain the function of l2 norm. Why use L2 norm first?

**Comment by gauenk** [comment]
Where do you see the l2 norm? E.g. file and line number?

**Comment by nzw0301** [comment]
@gauenk I think https://github.com/Spijkervet/SimCLR/blob/f75dc28ce1cf707124e77e99e5a7e4b3e967c734/modules/simclr.py#L48-L50 and cosine is here
https://github.com/Spijkervet/SimCLR/blob/f75dc28ce1cf707124e77e99e5a7e4b3e967c734/modules/nt_xent.py#L17

In default, this repo normalizes z twice as @BoPang1996 mentioned because
https://github.com/Spijkervet/SimCLR/blob/f75dc28ce1cf707124e77e99e5a7e4b3e967c734/config/config.yaml#L20 

Thus, we can make the code faster by set`False` to the argument in the config file.

**Comment by gauenk** [comment]
I see what you are saying. I think this makes sense to remove the normalization then.

**Comment by Spijkervet** [comment]
You're correct, the l2 normalization in `SimCLR/modules/simclr.py` is unnecessary when performing CosineSimilarity.

**Comment by Spijkervet** [comment]
Resolved in commit [cd28fd8b136bb060964fad036e5ccaa515c0a359](https://github.com/Spijkervet/SimCLR/commit/cd28fd8b136bb060964fad036e5ccaa515c0a359).

Thanks!
